### ISSUE TITLE
Req Granularity on App Removal

### ISSUE THREAD

**Issue by methanoid** [mirinsoft/spydish#2]
The program is brilliant but it removes NONE or ALL of the Metro apps... what about if I want to remove all except say Windows Mixed Reality app?

**Comment by Belim** [comment]
:blush: :ok_hand: 
I have reserved this feature for SharpApp https://github.com/mirinsoft/sharpapp only, 
As I've only use the app once, namely after updates/clean installs to get rid off the sponsered apps .

Maybe in one upcoming version but not yet because of other priorities
