### ISSUE TITLE
Disabled Telemetry & Windows Tips through O&O ShutUp10, but spydish says otherwise

### ISSUE THREAD

**Issue by AdKiller** [mirinsoft/spydish#3]
Telemetry is disabled according to O&O ShutUp10 1.8.1411 and Windows Privacy Dashboard WPD 1.3.1532, but analyzing with spydish 0.10.11 says it is not.

**Windows 10 1909**

![spydish](https://user-images.githubusercontent.com/13304436/83631508-e776ea00-a59d-11ea-9b28-80c9ae7b2840.jpg)
![oo1](https://user-images.githubusercontent.com/13304436/83631520-ec3b9e00-a59d-11ea-9bdb-1e9806d7bfea.jpg)
![oo2](https://user-images.githubusercontent.com/13304436/83631570-ffe70480-a59d-11ea-9a1b-d67f038a0522.jpg)
![WPD](https://user-images.githubusercontent.com/13304436/83631589-06757c00-a59e-11ea-8b72-1d42a4c82294.jpg)
![WPD2](https://user-images.githubusercontent.com/13304436/83631625-168d5b80-a59e-11ea-9e03-df2ef010f152.jpg)

**Comment by Belim** [comment]
Disabled Telemetry requires the services dmwappushsvc and diagtrack also to be disabled. Only then the Policy will be declared as active/configured. This also noted in the policy description when you move your mouse cursor over it

Windows Tips requires Windows Spotlight to be disabled as noted here
https://docs.microsoft.com/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services

and "DisableWindowsConsumerFeatures"
https://www.jorgebernhardt.com/turn-off-microsoft-consumer-experiences/
only then Spydish will recognize the policy as configured

I hope that this information helps

**Comment by AdKiller** [comment]
Thanks for your detailed reply.

I checked and Device Management Wireless Application Protocol (WAP) Push message Routing Service - dmwappushservice - **already Disabled**

but strangely, the following are NOT disabled/configured.

DisableWindowsSpotlightFeatures in HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\Windows\CloudContent - DisableWindowsSpotlightFeatures 

 User Configuration > Administrative Templates > Windows Components > Cloud Content > Turn off all Windows spotlight features

**Comment by Belim** [comment]
Spydish recognized the service "dmwappushservice" as "dmwappushsvc". This will be fixed in next release. Thank you!

Regarding the key "DisableWindowsSpotlightFeatures"
If possible the policies will be set for the Local System, so in this case Spydish is looking here **HKEY_LOCAL_MACHINE**\SOFTWARE\Policies\Microsoft\Windows\CloudContent - DisableWindowsSpotlightFeatures
