### ISSUE TITLE
Truncated column text in Analyze

### ISSUE THREAD

**Issue by ripgith** [mirinsoft/spydish#4]
Just started this app. The Analyze screen shows two columns - apparently the first is the policy and the second is whether configured or not. For whatever reason both of these columns are too short so the full text of the policy and configured message is not visible. I can't find a column size setting or slider.
[https://i.imgur.com/AqU8G2p.png
](url)

**Comment by Belim** [comment]
Looks like you set DPI Scaling to 200%, right?

**Comment by ripgith** [comment]
Correct. 17" laptop with 3840x2160 res.

**Comment by ripgith** [comment]
Whoops. Didn't mean to close....

**Comment by Belim** [comment]
:ok_hand: can confirm. I'll look for a fix in next releases.

**Comment by Radder124** [comment]
Yep, same thing for me with a 200% DPI

**Comment by Belim** [comment]
Please check build https://github.com/mirinsoft/spydish/releases/tag/0.13.1

**Comment by ripgith** [comment]
Thanks! Looks good.
