### ISSUE TITLE
Block Installation of new Microsoft Edge wrong Reg Key

### ISSUE THREAD

**Issue by Radder124** [mirinsoft/spydish#7]
"DoNotUpdateToEdgeWithChromium." instead of "DoNotUpdateToEdgeWithChromium"
I think the dot should be removed.

**Comment by Belim** [comment]
Damn, how could that happen :worried: This will be fixed immediately in the next release
Many thanks for reporting it to me :thumbsup:

**Comment by Belim** [comment]
Fixed here https://github.com/mirinsoft/spydish/releases/tag/0.13.1
