### ISSUE TITLE
Privacy: disable Windows Tips

### ISSUE THREAD

**Issue by Radder124** [mirinsoft/spydish#9]
This setting actually adds more than one reg Key (AllowSuggestedAppsInWindowsInkWorkspace for example) so I think it should be divided: "Block suggested Apps in Windows Ink Workspace" for the key above, ...

**Comment by Belim** [comment]
Ahh, this key remained when Spydish was not yet public. 
Thanks for the info. I will remove the setting from this policy and possibly build a second policy from it

**Comment by Radder124** [comment]
Cool. It adds 3 or 4 reg Keys so it may need a little reorganization :)

**Comment by Belim** [comment]
AllowSuggestedAppsInWindowsInkWorkspace key has been removed for the first in https://github.com/mirinsoft/spydish/releases/tag/0.13.1

**Comment by Radder124** [comment]
Just to know, did you delete the AllowSuggestedAppsInWindowsInkWorkspace key or did you move it somewhere else?
Maybe you can add it to a new setting "Block suggested Apps in Windows Ink Workspace" ?

**Comment by Belim** [comment]
Yes, I've removed the key.  
Would be feasible, will take a look in on of the upcoming versions.
I think that this is not a essential setting for surving Windows 10, i have never used the Ink Workspace myself
